### ISSUE TITLE
clang produces larger binaries than gcc for arm7

### ISSUE THREAD

**Issue by froydnj** [android-ndk/ndk#133]
We've been working on compiling Firefox for Android with clang lately and today I finally got everything to build with NDK r12 and clang today.  All the necessary patches aren't committed yet, so replicating this would be a bit tricky at the moment, but the end result is that our main library, `libxul.so`, compiled with clang is about 10% bigger than when we use gcc (text size, as measured by `size(1)`).  Our mobile team is quite concerned about our APK size already, and telling them that a mandated compiler switch would tack on another 3MB+ of size...well, let's just say they wouldn't be happy. :wink:

This result was pretty surprising, as we were expecting similar performance and even hoping for a codesize win.  I have verified that the build flags were identical in both builds (same `-O` options, `-fno-exceptions` turned on, `-ffunction-sections` + `-Wl,--gc-sections` turned on, both builds using `libc++`, etc.).  It is entirely possible that I've missed some key clang option, though I can verify that using `-funique-section-names` doesn't change the result.

Judging from a quick skim of diff'd `nm` output, the clang build has many more symbols, especially template methods.  I can't tell whether this is an effect of inlining heuristics, or of clang somehow keeping those symbols around when they're not actually used.

I apologize for not being able to provide replication instructions; I'll try to get all the necessary patches committed soon.  We had a workweek last week, and that's been a bit disruptive for getting code reviewed and committed.

Is this sort of difference something that you've seen in your own testing as well, or does this sound like an outlier?

**Comment by enh** [comment]
measured across the whole platform, the switch was a wash --- some devices were a few MiB smaller, some a few MiB larger. and that's out of ~1GiB+!

i think the ChromeOS folks are investigating switching atm, so i'll see if we can out more about their experience --- libwebview_chromium.so is orders of magnitude larger than the next largest library on the system (and we take prebuilts, so they won't have been affected by the rest of the platform switching).

out of interest --- do you build for x86/x86-64 too? do you see similar results there or is that better/worse?

**Comment by froydnj** [comment]
We build for x86 as well, but I haven't measured that.  I will do that and report back.

**Comment by stephenhines** [comment]
Which -O flags are you passing? Are you using -Os or just -O2? It would be really useful to know the common set of flags. One other question is are you stripping these binaries? Clang has larger debug info than GCC, but that shouldn't be a problem for shipped builds.

**Comment by froydnj** [comment]
We use `-Os` everywhere; the other interesting flags that we compile with are: `-fno-short-enums -fno-exceptions -march=armv7-a -mthumb -mfpu=vfp -mfloat-abi=softfp -mno-unaligned-access -fno-strict-aliasing -fno-rtti -ffunction-sections -fdata-sections -fno-math-errno`.

We link with `-Wl,-z,noexecstack -Wl,-z,text -Wl,--build-id -Wl,--icf=safe -Wl,--hash-style=sysv -Wl,--gc-sections`.

The measurements are done with unstripped binaries, but the measurements only look at things that wouldn't get stripped away; in the below output, `build-android` is a build with clang and `build-android-gcc` is a build with gcc:

```
froydnj@thor:/opt/build/froydnj/build-android$ size toolkit/library/libxul.so
   text	   data	    bss	    dec	    hex	filename
37104041	2331336	 192928	39628305	25cae11	toolkit/library/libxul.so
froydnj@thor:/opt/build/froydnj/build-android-gcc$ size toolkit/library/libxul.so
   text	   data	    bss	    dec	    hex	filename
33482353	2358544	 185792	36026689	225b941	toolkit/library/libxul.so
```

Or, if you prefer:

```
froydnj@thor:/opt/build/froydnj/build-android$ readelf -SW toolkit/library/libxul.so |egrep 'Size|text'
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [12] .text             PROGBITS        003537c0 3537c0 1b78544 00  AX  0   0 64
froydnj@thor:/opt/build/froydnj/build-android-gcc$ readelf -SW toolkit/library/libxul.so |egrep 'Size|text'
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [12] .text             PROGBITS        00344140 344140 1808bd0 00  AX  0   0 64
```

The first measurement with `size` includes a bunch of other things, like read-only strings and so forth.  The second measurement with `readelf` measures the size of the `.text` section straight-up, and shows a size increase of ~3.5MB, which is a ~14% increase of just executable code.

**Comment by jmgao** [comment]
Could you upload the gcc and clang-built binaries somewhere for comparison?

**Comment by froydnj** [comment]
> Could you upload the gcc and clang-built binaries somewhere for comparison?

Sure.  Is it a problem if I strip debug information but leave symbols?  My upload speed is terrible.

**Comment by jmgao** [comment]
I think that should be fine.

**Comment by froydnj** [comment]
I've uploaded them at https://people.mozilla.org/~nfroyd/libxuls.tar.bz2 .  That'll unpack into:

```
drwxr-xr-x froydnj/froydnj   0 2016-06-25 02:07 libxul-comparison/
-rwxr-xr-x froydnj/froydnj 69143396 2016-06-25 02:06 libxul-comparison/libxul-clang.so
-rwxr-xr-x froydnj/froydnj 66911236 2016-06-25 02:07 libxul-comparison/libxul-gcc.so
```

Please let me know if you need anything else.

**Comment by DanAlbert** [comment]
FYI, it sounds like the ChromeOS folks might have found something. It seems that clang is usually better or equivalent, but there are some pathological cases where it produces much larger binaries.

**Comment by stephenhines** [comment]
The ChromeOS issues are actually invalid, since they were omitting -mthumb, which isn't on by default for the clang target they are using. When they recompiled for Thumb-2, they got a 5.5% reduction vs. GCC on code size. Can you check to make sure that you are indeed using -mthumb throughout your build (and not putting -mno-thumb anywhere)?

**Comment by froydnj** [comment]
> Can you check to make sure that you are indeed using -mthumb throughout your build (and not putting -mno-thumb anywhere)?

We are using `-mthumb` everywhere; `-mno-thumb` is used nowhere in our build tree.  After a build, running the following command:

```
readelf -sW toolkit/library/libxul.so |grep FUNC |awk '$2 ~ /[048c]$/ {print}'
```

(that is, show me all the function symbols that have arm addresses; thumb addresses would have the lowest bit set and would match the regex `[159d]$`) shows only undefined symbols that will be resolved via dynamic linking, or a few symbols such as `__adddf3` and the like from `libgcc` or `compiler-rt`.  There's also a very few handwritten FFI stubs that don't come in thumb versions.  But all of these functions only add up to ~55K or so.

Eyeballing a build build log also shows that we are passing `-mthumb` everywhere that matters.

**Comment by DoDoENT** [comment]
In our company, we use exactly the same compile flags for both GCC and Clang, as described in #21.

**Comment by bog-dan-ro** [comment]
Any news on this matter?
I just tested Qt libs with clang (r13-beta2) and g++ (r10e) and clang **stripped** libs are +40% larger than g++ ones (of course using the same compile & link flags), which IMHO is way too much. Even supposing clang bins are +40% faster, which I sincerely doubt that, being +40% larger is still a big issue.

If anyone wants to test it, I can provide the steps to compile Qt to reproduce this problem.

**Comment by DanAlbert** [comment]
@pirama-arumuga-nainar: You'd looked at some of the other qt issues, could you take a look at the 40% (wat) size increase? Anything that bad probably has some pretty obvious causes...

**Comment by pirama-arumuga-nainar** [comment]
@bog-dan-ro Can you post instructions to reproduce?  It'd be great if you can isolate it to one or few object files with egregious increase, and post build commands with both gcc and clang.

**Comment by bog-dan-ro** [comment]
@pirama-arumuga-nainar they are almost the same instructions as https://github.com/android-ndk/ndk/issues/34#issuecomment-199681693

Sadly I compared the final **stripped** libs ...
This are the steps you need to do to build the entire Qt (some modules are less than 40% and some more):
```
$ git clone git://code.qt.io/qt/qt5.git -b 5.7.1
$ cd qt5
$ ./init-repository -f --ignore-submodules qtwebkit qtwebkit-examples  qtwebengine
```

Final step is to configure & compile Qt, you'll need Android NDK & SDK (with API-16 installed):

Build for with clang:
```
$ ./configure -developer-build -release -xplatform android-clang -nomake tests -nomake examples -android-ndk /path/to/NDKr13 android-sdk /path/to/SDK
$ make -j8 (you'll need to wait a few minutes)
```

The libs will be placed in qtbase/libs

Build for with g++:
```
$ ./configure -developer-build -release -xplatform android-g++ -nomake tests -nomake examples -android-ndk /path/to/NDKr10e android-sdk /path/to/SDK
$ make -j8 (you'll need to wait a few minutes)
```
Same as above, the libs will be placed in qtbase/libs

I'll do the same thing tomorrow, maybe I'll spot the object files that are way too big.

**Comment by bog-dan-ro** [comment]
@pirama-arumuga-nainar  QtXML seems the easiest to check it hs just a few .o files. You can find the .o files in ```qtbase/src/xml/.obj``` and from ```qtbase/src/xml``` you can  ```make clean all``` to see the command lines that are executed.

**Comment by DanAlbert** [comment]
@bog-dan-ro: Just looking at build output, you're not using `-ffunction-sections`, `-fdata-sections`, or `-Wl,--gc-sections` (I've tried adding them a few times, but there seem to be some races in the build system and both `make -B` and `make clean` fail for me, and re-running configure takes ages). That would definitely be the first step in shrinking your binaries.

Another thing worth noting, I see you're using C++1z with Clang. I hope you're not using anything higher than C++11 when building with GCC, because GCC 4.9's C++14 ABI is not correct (it's still a pre-final ABI that is no longer supported by GCC or by Clang).

**Comment by bog-dan-ro** [comment]
@DanAlbert ```-ffunction-sections  -fdata-sections``` does shrink the binaries size made by clang, but it shrinks also gcc bins even more :)

```
bogdan@zmeu:~/work/qt/qtbase/lib$ ls -l libQt5Xml.so 
-rwxr-xr-x 1 bogdan bogdan 120008 oct 27 13:55 libQt5Xml.so
bogdan@zmeu:~/work/qt/qtbase-clang/lib$ ls -l libQt5Xml.so 
-rwxr-xr-x 1 bogdan bogdan 197432 oct 27 13:54 libQt5Xml.so
```

As you can see the percentage is the same ~65% ...

To test it locally please apply https://paste.kde.org/pmagqlgvf  and ```make clean all```. No need to reconfigure!

**Comment by bog-dan-ro** [comment]
Sorry, the gcc bins are still the same. clang bins shrinked from 201532 to 197432, but still ~65% larger than gcc.

**Comment by pirama-arumuga-nainar** [comment]
@bog-dan-ro I am unable to build with Clang based on your instructions.  The ARM triple doesn't get passed to the .c files in harfbuzz.  If I do  configure with '-target ..' in CFLAGS, some files that get compiled with gcc throw an error.

**Comment by bog-dan-ro** [comment]
@pirama-arumuga-nainar did you used ndkr13 for clang?
I'm on IRC (freenode) #necessitas channel, please feel free to ping me if you need any help.

**Comment by pirama-arumuga-nainar** [comment]
@froydnj Just looking at the libxul shared objects takes me down a rabbit hole.  I definitely see differences in inlining in a few places.  Can you share build instructions or maybe a capture of the build commands for a single module?

@bog-dan-ro  Here's the list of commands I run:
```
git clone git://code.qt.io/qt/qt5.git -b 5.7.1 qt5-clang
cd qt5-clang
./init-repository -f --ignore-submodules qtwebkit qtwebkit-examples  qtwebengine
CFLAGS="-ffunction-sections -fdata-sections" ./configure -developer-build -release -xplatform android-clang -nomake tests -nomake examples -android-ndk <path-to-ndk-r13> -android-sdk <path-to-sdk>
make
```

I get the following error:
```
/ssd1/pirama/ndk-related/android-ndk-r13/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: .obj/harfbuzz-buffer.o: incompatible target
```

All the .c files in harfbuzz are targeted for x86_64.

**Comment by bog-dan-ro** [comment]
@pirama-arumuga-nainar You don't need to clone all the modules, qtbase is enough. I've updated the instructions a few days ago, please check https://github.com/android-ndk/ndk/issues/133#issuecomment-256569487 again.
Also make sure you replace ```/path/to/NDKr13``` and ```/path/to/SDK``` with the real paths :)

**Comment by bog-dan-ro** [comment]
@pirama-arumuga-nainar please use 5.6.2 branch instead, it seems we have some problems in 5.7.1 branch (sorry for not checking it earlier).

**Comment by pirama-arumuga-nainar** [comment]
@bog-dan-ro  Sorry, I am still seeing the same error.  Are you skipping harfbuzz because of differences in arguments to configure?  Can you try a clean checkout?

$ file ./qtbase/src/corelib/.obj/harfbuzz-gpos.o
./qtbase/src/corelib/.obj/harfbuzz-gpos.o:       ELF 64-bit LSB  relocatable, x86-64, version 1 (SYSV), not stripped

**Comment by pirama-arumuga-nainar** [comment]
@bog-dan-ro  To continue: The build rules are adding '-target armv7...' to CXXFLAGS but not to CFLAGS (see qtbase/src/corelib/Makefile).  This doesn't matter for gcc but breaks Clang build.

**Comment by bog-dan-ro** [comment]
@pirama-arumuga-nainar  strange ... because I'm setting all the compiller flags to CFLAGS and then I do CXXFLAGS=CFLAGS...

Let's check a few things:
- make sure you're using sha1: **65858057f0f769** (it's the head of 5.7.1 branch).
- make sure you clean the qtbase folder before you build it.
- I need the **exact** ```configure``` commands line arguments that you pass for **clang** and for **gcc**. If you can paste the output of both configure will be great.
- if it still fails it might be because it fails to find all the dependencies needed to build the host tools, in this case you need to install it's dependencies i.e. on debian like os ```$ sudo apt build-dep qtbase5-dev```.

I'll list you all the steps you need to perform for clang:
```
$ git clone git://code.qt.io/qt/qtbase.git -b 5.7.1 qtbase-clang
$ cp -a qtbase-clang qtbase-gcc
$ cd qtbase-clang
$ git checkout 65858057f0f769 -b test
$ git clean -d -f -x .
$ ./configure -xplatform android-clang -nomake tests -nomake examples -android-ndk /home/bogdan/android/android-ndk-r13 -android-sdk /home/bogdan/android/android-sdk -developer-build -release
$ make -j8
```

I'll list you all the steps you need to perform for gcc:
```
$ cd qtbase-gcc
$ git checkout 65858057f0f769 -b test
$ git clean -d -f -x .
$ ./configure -xplatform android-g++ -nomake tests -nomake examples -android-ndk /home/bogdan/android/android-ndk-r10e -android-sdk /home/bogdan/android/android-sdk -developer-build -release
$ make -j8
```

This is very strange, because you could build qtbase before ...

**Comment by pirama-arumuga-nainar** [comment]
@bog-dan-ro Thanks for the revised comments.  I am able to build now.  Earlier, I was setting CFLAGS while running configure.  Qt's build system seems to dislike this.

Seems like the gcc build uses -fno-exceptions while clang's doesn't.  With [this](http://pastebin.com/i49GJtLj) patch, the total size of Clang-built shared objects reduces to 17.5M from 19.5M.  Now, Clang's code size impact is down to 16% from 29% (in my setup, the size of gcc-built binaries totals to 15M).

**Comment by froydnj** [comment]
> @froydnj Just looking at the libxul shared objects takes me down a rabbit hole. I definitely see differences in inlining in a few places. Can you share build instructions or maybe a capture of the build commands for a single module?

@pirama-arumuga-nainar What do you mean by "capture of the build commands"?  Do you want preprocessed source for each compiler + command-line flags, or something else?

**Comment by bog-dan-ro** [comment]
@pirama-arumuga-nainar thanks for the patch, indeed using -fno-exceptions reduced the code (I was pretty sure that I'm using exception in gcc as well).
But if you check only ```libQt5Xml.so``` you'll see that it's still 33% larger.

I merged your patch with Dan's one and I added also the -O2 before -Os to make a perfect match between clang flags and gcc here https://paste.kde.org/pky512us5 is the patch.

Adding "-c++std c++11" to configure args will force the c++11 usage on both compilers.

**Comment by kmcgrath-cd** [comment]
If we're just discussing the raw size of the .so files (not the actual .text section inside the .so), my research has shown that moving from GCC to clang (r14b, Windows 10 64-bit) increases our .so 47%!  This is after being stripped of any symbols except for 32 functions we need to call from Java.  The .text sections themselves only grew 11%, which I could live with, but there are several sections that grew obscene amounts.  The worst offender in terms of raw size is the .dynstr section, which grew 1,041% (from 151KB to 1.7MB!!).  .rel.plt and .plt both grew over 6,800%.  Why in the world would a clang compiled .so need so much more relocation information than the same exact project built with GCC?

**Comment by stephenhines** [comment]
kmcgrath-cd, can you provide more information about your application (especially if it is publicly available/buildable)? We would want to reproduce this issue, but I suspect that you are using some command line flags that are retaining things that should be optimized out.

**Comment by kmcgrath-cd** [comment]
Here are more details on a less troubled game of ours, built using `ndk-build NDK_DEBUG=0` using NDK r14b with only changing `NDK_TOOLCHAIN_VERSION` from `4.9` to `clang` (and no other changes):
```
GCC                    GCC      GCC         clang                  clang    clang         
Name                   Size     Size in Dec Name                   Size     Size in Dec  % diff
.interp                00000013          19 ---------------------- -------- -----------  ----
.note.gnu.build-id     00000024          36 .note.gnu.build-id     00000024          36    0%
.dynsym                00075110     479,504 .dynsym                00071e60     466,528   -3%
.dynstr                0013bb38   1,293,112 .dynstr                0014eb85   1,371,013    6%
.hash                  0002d4b8     185,528 .hash                  0002c80c     182,284   -2%
.gnu.version           0000ea22      59,938 .gnu.version           0000e3cc      58,316   -3%
.gnu.version_d         0000001c          28 .gnu.version_d         0000001c          28    0%
.gnu.version_r         00000060          96 .gnu.version_r         00000060          96    0%
.rel.dyn               00053e58     343,640 .rel.dyn               000545f8     345,592    1%
.rel.plt               00000ac0       2,752 .rel.plt               00024cc8     150,728   98%
.plt                   00001034       4,148 .plt                   00037340     226,112   98%
.text                  00573708   5,715,720 .text                  0064166a   6,559,338   13%
.ARM.extab             0003162c     202,284 .ARM.extab             0007c850     510,032   60%
.ARM.exidx             00020388     131,976 .ARM.exidx             00023a60     146,016   10%
.rodata                000a3a68     670,312 .rodata                000a5000     675,840    1%
.data.rel.ro.local     0000b598      46,488 .data.rel.ro.local     000093a8      37,800  -23%
.fini_array            00000008           8 .fini_array            00000008           8    0%
.init_array            00000188         392 .init_array            00000160         352  -11%
.data.rel.ro           00026160     156,000 .data.rel.ro           00027aa0     162,464    4%
.dynamic               00000148         328 .dynamic               00000140         320   -3%
.got                   00002e94      11,924 .got                   00014f88      85,896   86%
.data                  00007600      30,208 .data                  00007260      29,280   -3%
.bss                   000113d4      70,612 .bss                   00011334      70,452    0%
.comment               00000099         153 .comment               00000099         153    0%
.note.gnu.gold-version 0000001c          28 .note.gnu.gold-version 0000001c          28    0%
.ARM.attributes        0000003c          60 .ARM.attributes        0000003c          60    0%
```
.so file sizes:
```
clang: 11,012,260 bytes
GCC:    9,337,972 bytes
diff:   1,674,288 bytes  18% larger
```
Not nearly as dramatic as our other game, but as you see above both `.rel.plt` and `.plt` both are dramatically larger, as well as `.ARM.extab` and `.got`.

Also please note, the `.text` section is 8 byte aligned for GCC byte 16 byte aligned for clang, which could also be contributing to the increased size of the `.text` section.

Here are the relevant `Application.mk` settings:
```
APP_ABI         := armeabi-v7a
APP_CPPFLAGS    := -std=c++11 -fexceptions -frtti -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-unknown-warning-option
APP_CFLAGS      := -Wno-nonportable-include-path -Wno-unknown-warning-option
APP_PLATFORM    := android-9
APP_PIE         := false
NDK_TOOLCHAIN_VERSION   := 4.9 / clang
APP_STL                 := c++_static
```

Again, the only difference between these two builds is a simple swap from `4.9` to `clang`.

**Comment by DanAlbert** [comment]
This got mentioned on the other thread (https://github.com/android-ndk/ndk/issues/21), but I don't think anyone has tried it: try adding `-Bsymbolic` to your ldflags when using Clang? This is on by default with GCC, but it's a bad default so we've fixed that in Clang. It will be responsible for *some* increase. How much of an increase will vary by shared library (if you have millions of trivial functions that are all public, it will have a huge impact, if you have a single large function, the impact will be roughly nil).

**Comment by kneth** [comment]
I guess inlined functions count, right? So we should use old C macros instead 😢

**Comment by kmcgrath-cd** [comment]
I just performed two clean release (not debug) builds, one using -Bsymbolic for a linker parameter and the other build without the -Bsymbolic linker parameter, and here are the results (raw .SO size):
```
With -Bsymbolic
13,858,008 bytes

Without -Bsymbolic
13,858,008 bytes
```

**Comment by DanAlbert** [comment]
@kneth: No, inline functions or static functions shouldn't count aiui. Only things that are able to be replaced by other shared libs.

@kmcgrath-cd: Hrm. My contrived examples show pretty much the same thing. @dimitry-: what are the circumstances where this takes effect?

**Comment by nico** [comment]
For chrome, we had to use -Oz instead of -Os when building with clang. With -Oz, chrome built with clang was smaller and did better on our benchmarks, however.

**Comment by kmcgrath-cd** [comment]
Using -Oz instead of -Os did indeed reduce the size of our binary, but only by like 2%:

```
With -Os: 13,603,992 bytes
With -Oz: 13,326,172 bytes
-Oz Saves 277,820 bytes
```

**Comment by DanAlbert** [comment]
@froydnj: I see mozilla has switched to using -Oz in some cases. Do your findings match with @kmcgrath-cd's (improvment, but gcc is still smaller)? I was able to repro the 15% increase with [one of our samples](https://github.com/googlesamples/android-ndk/tree/master/san-angeles/app/src/main/cpp), but switching to -Oz made both of them more or less the same size (+28 bytes, 0.2%, definitely in the noise).

Has anyone else been able to try this? @kneth @DoDoENT @bog-dan-ro?

At this point we lack data to do much on this, so please let us know!

**Comment by froydnj** [comment]
@DanAlbert We have found that clang (NDK 15b, `-Oz`) produces ~0.7% smaller code than gcc (`-Os`).  Given that, if we can show identical performance between the two, we're planning on switching, which will also unblock other initiatives (e.g. compiling with `-std=c++14`).

**Comment by DanAlbert** [comment]
That's good news! Let us know what you find benchmark-wise. Will wait to hear from a couple others before closing this one out.

@kmcgrath-cd: Any chance only some of your code was rebuilt with `-Oz`? Or you're missing `-ffunction-sections`/`-fdata-sections` or something like that?

**Comment by bog-dan-ro** [comment]
@DanAlbert we've switched to -oz and now clang bins are "just" ~10% larger than gcc ones. 
IMHO you should keep this bug opened until clang bins are  -5% larger than gcc ones.

**Comment by DoDoENT** [comment]
In my case with `-Oz` the binary is around 9% smaller than with `-Os`, but `12%-20%` slower (depending on use-case).

I cannot compare against GCC anymore because my codebase requires some c++17 features, which are not available with GCC 4.9.

**Comment by kmcgrath-cd** [comment]
Compiling with: `-Oz ... -fdata-sections -ffunction-sections`
Linking with: `-Wl,--gc-sections`

Using NDK r14b:
Without Data or Function Sections: 13,473,884 bytes
With Data and Function Sections: 13,420,540 bytes
Data and Function Sections Saves: 53,344 bytes

Using NDK r15c:
With Data and Function Sections: 13,482,160 bytes
Using Data and Function Sections with r15c increased by +8,276 bytes over unsing no sections with r14b.

All three builds seem to run just fine, but it's just not the big savings I had hoped for, and switching to NDK r15c actually increases our final .so size.

**Comment by DanAlbert** [comment]
Thanks for the additional data. Sounds like there's still more to do here.

Does anyone have a test case they can contribute? I'll check the rest of the samples to see if they're just an `-Os` vs `-Oz` issue, but having a test case from one of you (with source, preferably) would help a lot.

**Comment by stephenhines** [comment]
A "reduced" test case (single source file + command line flags) would be really helpful. It is very difficult for us to integrate/test with an arbitrary build system. Having something standalone allows us to work better with upstream committers too (and such a case can eventually be anonymized, etc., and turned into a proper regression test).

**Comment by kmcgrath-cd** [comment]
So I think I've found a big clue.  I managed to reduce my games .so size by 4MB, from 13MB to 9MB, by using a few more compiler options and one more linker option.  The table below shows all of the before and after tests.  The column "r14b" is .so section sizes for our normal build for this game, "r14b Sec" uses the additional compiler options `-fdata-sections -ffunction-sections` and the additional linker options `-Wl,--gc-sections`, the section "r15c" is simply a rebuild using the latest NDK (r15c), and the last column "r14b All" uses these additional compiler options **`-fdata-sections -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden`** and this additional linker option **`-Wl,--gc-sections`**.  The last column is the percent savings from the "r14b" column to the "r14b All" column, or how much using all of these compiler and linker options combined saves.

```
Idx Name                         r14b    r14b Sec        r15c   r14b All
0   .note.gnu.build-id             36          36          36         36   0%
1   .dynsym                   652,208     652,208     647,136     96,784  85%
2   .dynstr                 1,999,170   1,999,170   1,974,312    177,714  91%
3   .hash                     294,144     294,144     292,876     40,600  86%
4   .gnu.version               81,526      81,526      80,892     12,098  85%
5   .gnu.version_d                 28          28          28         28   0%
6   .gnu.version_r                 96          96          96         96   0%
7   .rel.dyn                  431,864     427,408     429,408    387,856  10%
8   .rel.plt                  221,920     221,576     218,568     21,504  90%
9   .plt                      332,900     332,384     327,872     32,276  90%
10  .text                   7,271,288   7,230,300   7,387,364  6,715,808   8%
11  .ARM.extab                787,504     784,516     867,676    718,716   9%
12  .ARM.exidx                208,232     206,160     203,192    178,944  14%
13  .rodata                   785,517     785,389     647,149    774,141   1%
14  .data.rel.ro.local          3,480       3,056       3,056      3,056  12%
15  .fini_array                     8           8           8          8   0%
16  .data.rel.ro              241,924     238,924     238,840    225,916   7%
17  .init_array                   404         404         404        404   0%
18  .dynamic                      328         328         328        328   0%
19  .got                      125,208     125,004     124,532     16,732  87%
20  .data                      33,320      33,224      33,344     31,884   4%
21  .bss                       90,308      70,996      71,028     52,996  41%
22  .comment                      138         138         199        138   0%
23  .note.gnu.gold-version         28          28          28         28   0%
24  .ARM.attributes                60          60          60         60   0%
    Total                  13,561,639  13,487,111  13,548,432  9,488,151  30%

```
I'd like to point out that several sections having to do with relocation dropped dramatically.

The game still works just fine, so I think we're going to continue using these options.

You should be able to reproduce these results, but it will take a large example app.  I doubt it will show much of a difference on a one file example app, you'll need a lot of functions, a lot of C++ usage, etc.  In otherwords, you'll need a real-world example.

**Comment by DanAlbert** [comment]
Yeah, marking things as hidden will let the linker strip a lot more things from your final library (if it's public the linker doesn't know if it will be called by something else, but it only has to check the binary itself to know if a hidden function will be called).  `-fvisibility=hidden` or a version script are both good ways to do this.

**Comment by kmcgrath-cd** [comment]
What's interesting, to me at least, is that `-fvisiblity=hidden` didn't remove any of the C++ functions that had been declared public (or rather not declared as static), so everything I needed to call before was still there; there's still a large dynamic symbol table for the .so.  But what it did do was dramatically reduce the junk that was sitting inside the relocation sections of the .so.  Notice all of the sections that dropped by 80%+ in size.  That stuff has nothing to do with function visibility.  I firmly believe that there's a bug in clang that, without `-fvisibility=hidden` being enabled, it will add a massive amount of relocation information for each symbol, and I believe that the NDK should default to using `-fvisibility=hidden` as a compiler option.

In other words, I didn't actually hide anything more than I was already hiding, but I did seem to trigger clang to not generate so much relocation garbage.  Now it's much closer to what you would get with GCC.

**Comment by kmcgrath-cd** [comment]
Correction: Running nm -C -D on the before and after .so file showed me that the before .so had 40,762 dynamic symbols exposed, while the after .so has 6,052 dynamic symbols exposed.  So it seems that the default nature of clang is to expose everything not explicitly declared as static to be available, while GCC is only exposing those symbols declared as extern to be public, and clang goes back to GCC behavior when you add the `-fvisibility=hidden` option.  I'm not 100% sure, but I do know that something is very much amiss between GCC and clang in the NDK.

**Comment by DanAlbert** [comment]
That sounds a lot like the `-Bsymbolic` differences.

**Comment by DanAlbert** [comment]
FYI, as far as we know this is fixed in r16. Our build systems now use `-Oz` instead of `-Os` for clang, and GCC no longer defaults to `-Bsymbolic`. If you're not using ndk-build or our cmake toolchain, make sure you switch over to `-Oz` for Clang. The GCC change is built into the toolchain (or rather, the Android specific hack was removed from the toolchain), so you don't need to make any change on your end.

The result you should see is a smaller binary produced by Clang in comparison to r15, and a larger (potentially much larger, depending on how many relocations your library has) binary produced by GCC compared to r15. If this is the case, you can get the size savings back by adding `-Bsymbolic` to your ldflags.

Also make sure you have `-fdata-sections`, `-ffunction-sections` in your cflags and `-Wl,--gc-sections` in your ldflags (ndk-build and our cmake toolchain do this by default, but custom build systems will need to do it themselves, and I don't know about upstream cmake).

In the cases I've looked at, these two changes won back all the size differences between GCC and Clang, so if you're still seeing huge differences between GCC and Clang in r16, please let us know.

**Comment by chri7325** [comment]
Unfortunately for our product, I'm still seeing quite a massive increase in size.  For armv7 release, the GCC size is 34MB while the clang ones is 42MB.  We use the standalone compiler toolchains so there is no -Bsymbolic issues there.  Adding/removing it didn't really make any notable difference in either library.  I did also try using Oz and was able to take 3MB off of the clang binary but performance tests showed an 8% negative affect on performance so we did not think it was worth the size savings.  I really want to move to clang but this issue is the only thing holding us back.  I had also hoped to use thinLTO to try to reduce the size even more but got a lot of strange linker errors.  I had tried this with r16beta1 so if the r16 release has made significant changes, I can give it another test.

**Comment by DanAlbert** [comment]
@chri7325: beta 1 did not have the changes.

**Comment by chri7325** [comment]
@DanAlbert unfortunately even with r16 release, I'm still getting the same size.  I tried with the standalone toolchains as well as with ndk-build.  Here's a sample of my Application.mk.  function sections isn't listed as it is implicitly added by the ndk-build system.
```
APP_STL := c++_static
NDK_TOOLCHAIN_VERSION := clang
APP_CPPFLAGS += -std=c++14 -frtti -fexceptions -fdata-sections -fvisibility=hidden -fvisibility-inlines-hidden
APP_LDFLAGS += -Wl,--gc-sections

# To build other architectures, uncomment a different APP_ABI and APP_PLATFORM and comment out these
APP_ABI := armeabi-v7a
APP_PLATFORM := android-16

#APP_ABI := x86
#APP_PLATFORM := android-16

#APP_ABI := arm64-v8a
#APP_PLATFORM := android-21

# To build android for release, change APP_OPTIM to release. To debug the application, build with NDK_DEBUG=1 on the command line.
APP_OPTIM := release
```

**Comment by DanAlbert** [comment]
@chri7325: That's unfortunate. Just to be crystal clear, those numbers are for a GCC that's also from r16, right? Not r16 clang vs r10 GCC or something like that?

Are you able to provide a test case? As far as I know, we do not currently have even a single test case that actually can be built with both GCC and Clang.

At one point we had one for Qt, but it was an out of date Qt even then and required a handful of other in-progress patches for Clang support, and last time I tried, the steps provided didn't work. @bog-dan-ro: have you tried with the latest release? Could you provide updated repro steps for us?

@froydnj: Last time I'd tried building firefox with clang it was also a no go because mach wasn't ready for clang (at least not with an up to date ndk). Has that changed?

Otherwise, you can try using https://github.com/google/bloaty to narrow down where the space is going. I'm most interested in the results from using ndk-build for this, since that is I think the first time someone has reported this problem when using one of our build systems.

**Comment by chri7325** [comment]
@DanAlbert yes.  Those numbers are slightly outdated as we've grown a bit more.  Using GCC, my lib is 36MB and goes up to 44MB using clang.  Unfortunately, I can't provide a case due to IP issues.  I'll see if there are any open source tools that we build that exhibit the same behavior.

**Comment by bog-dan-ro** [comment]
@DanAlbert I just test it and gcc still has better results:
```
gcc (ndkr10) ~15 smaller than clang
gcc (ndkr16) ~10 smaller than clang
```

These are the steps to compile QtBase. If you want to compile the entire Qt follow steps 4 & 5 from http://wiki.qt.io/Android

You need Android SDK (with tools & SDK platform +16) & android NDK
These are my installed packages:
```
$ ~/android/tools/bin/sdkmanager --list
Warning: File /home/bogdan/.android/repositories.cfg could not be loaded.       
Installed packages:=====================] 100% Computing updates...             
  Path                 | Version      | Description                    | Location             
  -------              | -------      | -------                        | -------              
  build-tools;26.0.1   | 26.0.1       | Android SDK Build-Tools 26.0.1 | build-tools/26.0.1/  
  emulator             | 26.1.4       | Android Emulator               | emulator/            
  ndk-bundle           | 16.0.4442984 | NDK                            | ndk-bundle/          
  patcher;v4           | 1            | SDK Patch Applier v4           | patcher/v4/          
  platform-tools       | 26.0.2       | Android SDK Platform-Tools     | platform-tools/      
  platforms;android-26 | 2            | Android SDK Platform 26        | platforms/android-26/
  tools                | 26.1.1       | Android SDK Tools              | tools/               
```
**I also unzipped NDK r10 in `~/android/android-ndk-r10e`**


Checkout QtBase 5.9 branch (5.9 is stable and you should have no surprises)
`$ git clone git://code.qt.io/qt/qtbase.git -b 5.9`

Shadow build for clang, make sure your replace **~/android/ndk-bundle** and **~/android** with your own paths.
```
$ mkdir build-clang
$ pushd build-clang
$ ../qtbase/configure -nomake tests -nomake examples -release -confirm-license -opensource -xplatform android-clang -android-ndk ~/android/ndk-bundle -android-sdk ~/android 
$ make -j`nproc`
$ cd lib
$ find *.so | xargs ~/android/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip -s
$ ls -l *.so
$ popd
```


Shadow build for gcc, make sure your replace **~/android/android-ndk-r10e** and **~/android** with your own paths
```
$ mkdir build-gcc
$ pushd build-gcc
$ ../qtbase/configure -nomake tests -nomake examples -release -confirm-license -opensource -xplatform android-g++ -android-ndk ~/android/android-ndk-r10e -android-sdk ~/android/
$ make -j`nproc`
$ cd lib
$ find *.so | xargs ~/android/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip -s
$ ls -l *.so
$ popd
```
**Tweaking the compilation flags. There are a few files involved:**
1. `qtbase/mkspecs/common/android-base-head.conf`  - This file is common to gcc & clang, usually you don't need to do any changes here.
2. `qtbase/mkspecs/android-clang/qmake.conf` - CLang specific settings
3. `qtbase/mkspecs/android-g++/qmake.conf` - gcc specific settings
4. `qtbase/mkspecs/common/android-base-tail.conf`  - This file is common to gcc & clang, it contains compile & linking flags that will be used by both compilers.

If you'll do changes to the above files which helps, please don't be shy and upstream them ;-)

**Comment by DanAlbert** [comment]
Thanks, was able to build with those. I'll see what I can find.

**Comment by DanAlbert** [comment]
The compiler isn't the only thing that changes when you switch to `-xplatform android-clang`. You're also switching STLs and C++ standard versions, among a handful of other minor things.

Switching from gnustl to libc++ likely does increase the size of your binaries because it depends on libandroid_support, which is a static library that includes implementations for things missing on old libc releases that libc++ depends on.

Switching from C++14 to C++1z may be building in additional features that are increasing the size of the binary.

I don't have anything concrete, but at the very least I'm suspicious of the assertion that clang is at fault here. It may very well be the case, but Qt is making enough other changes when changing compilers that it's far from conclusive.

Also, what's the right way to rebuild Qt after changing compiler flags? Just `make` doesn't do anything because apparently the outputs don't properly depend on their build configuration. I've been settling for `make -B -j48 -k; make -j48` (there's also a race...) but that's not ideal.

**Comment by DanAlbert** [comment]
I think I was able to isolate those issues. I copied the generated headers and source trees into an ndk-build project that builds just libQt5Xml.so, and I still see the growth.

bloaty shows a whole bunch of growth in the unwind tables, and some in text.

```bash
$ bloaty clang_stripped.so -- gcc_stripped.so
     VM SIZE                          FILE SIZE
 ++++++++++++++ GROWING            ++++++++++++++
   +10% +7.22Ki .text              +7.22Ki   +10%
  +980% +5.86Ki .ARM.extab         +5.86Ki  +980%
   +43% +1.75Ki .ARM.exidx         +1.75Ki   +43%
  +1.0%     +60 .rodata                +60  +1.0%

 -------------- SHRINKING          --------------
 -16.7%    -648 .plt                  -648 -16.7%
 -50.0%      -3 [Unmapped]            -586 -95.0%
 -16.8%    -432 .rel.plt              -432 -16.8%
 -11.4%    -392 .rel.dyn              -392 -11.4%
 -17.7%    -368 .data.rel.ro          -368 -17.7%
 -15.3%    -208 .got                  -208 -15.3%
  -0.5%    -114 .dynstr               -114  -0.5%
  -9.4%     -32 [ELF Headers]         -112  -7.5%
  -1.0%     -96 .dynsym                -96  -1.0%
  [ = ]       0 .shstrtab              -27  -8.8%
  [DEL]     -24 .data.rel.ro.local     -24  [DEL]
  -0.5%     -24 .hash                  -24  -0.5%
  [DEL]     -19 .interp                -19  [DEL]
  -1.0%     -12 .gnu.version           -12  -1.0%
  [ = ]       0 .ARM.attributes         -2  -3.3%

  +9.6% +12.6Ki TOTAL              +11.9Ki  +8.9%
```

Symbol size analysis is interesting too (unstripped, but this is comparing the size of the functions, not the debug sections):

```bash
$ bloaty -d symbols clang.so -- gcc.so
     VM SIZE                                                                             FILE SIZE
 ++++++++++++++ GROWING                                                               ++++++++++++++
   +45% +11.8Ki [Other]                                                               +11.8Ki   +45%
  [NEW]    +200 QList<QString>::detach_helper_grow                                       +200  [NEW]
  [NEW]    +184 QList<QDomNodePrivate*>::detach_helper_grow                              +184  [NEW]
  [NEW]    +176 QList<QXmlAttributes::Attribute>::detach_helper_grow                     +176  [NEW]
  [NEW]    +168 QVector<QMap<QString, QString> >::append                                 +168  [NEW]
  [NEW]    +144 QHash<QString, QHash<QString, int> >::operator[]                         +144  [NEW]
   +43%    +140 fixedXmlName                                                             +140   +43%
   +90%    +140 QDomDocumentTypePrivate::replaceChild                                    +140   +90%
  [NEW]    +132 QHash<QString, int>::insert                                              +132  [NEW]
  [NEW]    +130 QMap<QString, QXmlSimpleReaderPrivate::ExternParameterEntity>::insert    +130  [NEW]
   +86%    +124 QDomNamedNodeMapPrivate::setNamedItemNS                                  +124   +86%
  [NEW]    +124 QHash<QString, QHashDummyValue>::insert                                  +124  [NEW]
   +23%    +120 QDomImplementation::createDocumentType                                   +120   +23%
   +91%    +120 QDomNamedNodeMapPrivate::setNamedItem                                    +120   +91%
  [NEW]    +116 QList<QString>::erase                                                    +116  [NEW]
  [NEW]    +112 QMap<QString, QString>::operator[]                                       +112  [NEW]
   +16%     +92 QDomEntityPrivate::save(QTextStream&, int, int) const                     +92   +16%
   +81%     +88 QDomNamedNodeMapPrivate::removeNamedItem                                  +88   +81%
   +91%     +84 QDomDocumentTypePrivate::removeChild                                      +84   +91%
  [NEW]     +78 QExplicitlySharedDataPointer<QDomImplementationPrivate>::operator=        +78  [NEW]
   +76%     +76 QDomDocumentTypePrivate::insertAfter                                      +76   +76%

 -------------- SHRINKING                                                             --------------
 -22.5% -4.19Ki [Other]                                                               -4.19Ki -22.5%
 -39.4%    -452 QXmlSimpleReaderPrivate::isExpandedEntityValueTooLarge                   -452 -39.4%
 -20.5%    -276 QXmlSimpleReaderPrivate::parsePI                                         -276 -20.5%
 -65.3%    -248 QXmlAttributes::append                                                   -248 -65.3%
 -19.4%    -248 QXmlSimpleReaderPrivate::parseAttType                                    -248 -19.4%
 -11.0%    -220 QXmlSimpleReaderPrivate::parseEntityDecl                                 -220 -11.0%
 -16.3%    -192 QXmlSimpleReaderPrivate::parseElementDecl                                -192 -16.3%
  [DEL]    -184 QSet<QString>::insert                                                    -184  [DEL]
 -95.5%    -168 QXmlNamespaceSupport::pushContext                                        -168 -95.5%
 -68.9%    -168 QList<QString>::append                                                   -168 -68.9%
 -14.9%    -164 QXmlSimpleReaderPrivate::parseProlog                                     -164 -14.9%
 -78.0%    -156 QList<QDomNodePrivate*>::append                                          -156 -78.0%
  -9.4%     -32 [ELF Headers]                                                            -152  -7.5%
 -18.4%    -152 QXmlSimpleReaderPrivate::parseExternalID                                 -152 -18.4%
 -17.5%    -144 QXmlSimpleReaderPrivate::parseMarkupdecl                                 -144 -17.5%
 -12.0%    -136 QXmlSimpleReaderPrivate::parseAttlistDecl                                -136 -12.0%
  -9.7%    -104 QXmlSimpleReaderPrivate::parseDoctype                                    -104  -9.7%
 -54.3%    -100 QXmlNamespaceSupport::popContext                                         -100 -54.3%
 -15.3%    -100 QXmlSimpleReaderPrivate::parseMisc                                       -100 -15.3%
  [DEL]     -96 vtable for QXmlReader                                                     -96  [DEL]
  -6.6%     -92 QXmlSimpleReaderPrivate::parseContent                                     -92  -6.6%

 -+-+-+-+-+-+-+ MIXED                                                                 +-+-+-+-+-+-+-
   +10% +5.78Ki [Unmapped]                                                             -259Ki -16.9%

  +9.6% +12.6Ki TOTAL                                                                  -252Ki -15.7%
```

(note that "Other" means all the things that didn't fit in this printout, it's not some giant unknown function)

I'm not entirely sure what "unmapped" refers to. Given that a lot of functions are marked DEL or NEW between gcc and clang, I'm guessing those are the inlined functions? bloaty's docs aren't helpful.

Yes, that's a 15.7% size *decrease* for Clang. Whatever is accounting for the increase in text size, it's not showing up in this view.

@bog-dan-ro: do you see increases for other architectures, or just arm7?

I've attached stripped and unstripped binaries if anyone wants to take a look, but I'm done looking at this for the day.

[binaries.zip](https://github.com/android-ndk/ndk/files/1480761/binaries.zip)

**Comment by bog-dan-ro** [comment]
> The compiler isn't the only thing that changes when you switch to -xplatform android-clang. You're also switching STLs and C++ standard versions, among a handful of other minor things.
> 
> Switching from gnustl to libc++ likely does increase the size of your binaries because it depends on libandroid_support, which is a static library that includes implementations for things missing on old libc releases that libc++ depends on.

Well, personally I wanted to stick with gnu's libc++ but a lot of people got scared when you threat the you'll nuke gnu's libc++, so I gave up the pressure and I switch clang to libc++ ;-).

Regarding that static library that you talk about, that was my hunch too, but, no parts of it should be added any Qt libs because Qt doesn't use any of them. Let me know if you want to switch back gnu's libc++ to point you where and what to change.

> Switching from C++14 to C++1z may be building in additional features that are increasing the size of the binary.

Qt depends on C++11 only. I rebuilt clang with c++14 (add ` -c++std c++14 ` to configure params) and it has the same size.

> Also, what's the right way to rebuild Qt after changing compiler flags?

Ah, I forgot to mention that `qmake` doesn't _see_ compilation flags changes so, you need to do a `make clean; make -j48` to recompile it.

> do you see increases for other architectures, or just arm7?

Only arm* platforms. Incredibly for x86* clang creates smaller bins. Sadly it doesn't help because, well, 99% of android devices use arm* procs.

I created a small scrip with compiles QtBase on all clang supported platforms (armeabi armeabi-v7a arm64-v8a x86 x86_64), this way it will be easier for you to check them all

```
#!/bin/bash -x

ANDROID_NDK_PATH=~/android/ndk-bundle
ANDROID_NDKr10_PATH=~/android/android-ndk-r10e
ANDROID_SDK_PATH=~/android

function build {
    rm -fr build-$2-$1
    mkdir build-$2-$1
    pushd build-$2-$1
    ../qtbase/configure -nomake tests -nomake examples -release -c++std c++14 -confirm-license -opensource -xplatform android-$2 -android-ndk-platform android-21 -android-arch $1 -android-ndk $ANDROID_NDK_PATH -android-sdk $ANDROID_SDK_PATH
    time make -j`nproc`
    cd lib
    find *.so | xargs $$ANDROID_NDK_PATH/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip -s
    popd
}

for cpu_arch in armeabi armeabi-v7a arm64-v8a x86 x86_64
do
    build $cpu_arch clang
    build $cpu_arch g++
done
```

**Comment by bog-dan-ro** [comment]
@DanAlbert `make clean; make` is enough in any src folder you want e.g. if you want to recompile only Qt5Core library:
```
$ cd src/corelib
$ make clean; make -j40
```
it's enough.

**Comment by wang-bin** [comment]
You can build ffmpeg with --enable-small which use -Oz for clang. There's no c++ codec. so libandroid_support.a is not included. But clang still produces larger binaries for desktop linux and android.

**Comment by DanAlbert** [comment]
> But clang still produces larger binaries for desktop linux

ARM or x86/x86_64? We've only heard of increases for arm32 so far (and all the cases I've looked at actually show a size decrease for non-arm32).

**Comment by wang-bin** [comment]
> ARM or x86/x86_64? We've only heard of increases for arm32 so far

arm32

**Comment by rprichard** [comment]
I looked at Qt 5.9 using @bog-dan-ro's script, I and noticed a few things. Looking only at `libQt5Core.so` and `-android-arch armeabi-v7a`, `gcc -Os` is smaller than `clang -Oz`, which is smaller than `clang -Os`:
```
-rwxr-x--- 1 rprichard eng 3669048 Dec  7 18:58 out-gcc/core.so.stripped
-rwxr-x--- 1 rprichard eng 4026744 Dec 15 15:12 out-Oz/core.so.stripped
-rwxr-x--- 1 rprichard eng 4423260 Dec  7 20:07 out-Os/core.so.stripped
```
I'm using `strip -s` on each binary.

Here's the bloaty section comparison:

```
$ bloaty out-Oz/core.so.stripped  -- out-gcc/core.so.stripped 
     VM SIZE                          FILE SIZE
 --------------                    --------------
  +206%  +181Ki .ARM.extab          +181Ki  +206%
   +14%  +176Ki .text               +176Ki   +14%
 +57e2% +87.8Ki .data              +87.8Ki +57e2%
   +49% +24.0Ki .ARM.exidx         +24.0Ki   +49%
   +94% +14.1Ki .data.rel.ro       +14.1Ki   +94%
  +4.5% +1.55Ki .rel.dyn           +1.55Ki  +4.5%
  +2.6%    +289 .bss                     0  [ = ]
  [ = ]       0 .comment               +61  +152%
  [ = ]       0 .shstrtab              -27  -9.4%
  -7.1%     -23 [4 Others]             -37  -9.6%
  -9.4%     -32 [ELF Headers]         -112  -7.7%
  -2.1%    -262 .gnu.version          -262  -2.1%
  -1.3%    -524 .hash                 -524  -1.3%
  -8.6% -1.28Ki .got               -1.28Ki  -8.6%
  -2.1% -2.05Ki .dynsym            -2.05Ki  -2.1%
 -10.2% -2.73Ki .rel.plt           -2.73Ki -10.2%
  -1.7% -3.82Ki .dynstr            -3.82Ki  -1.7%
   +43%      +6 [Unmapped]         -3.83Ki -97.8%
 -10.2% -4.10Ki .plt               -4.10Ki -10.2%
  [DEL] -13.6Ki .data.rel.ro.local -13.6Ki  [DEL]
  -6.2%  -103Ki .rodata             -103Ki  -6.2%
  +9.9%  +353Ki TOTAL               +349Ki  +9.7%
```

Some things I noticed:

 * GCC defaults to `-fomit-frame-pointer`, whereas Clang defaults to `-fno-omit-frame-pointer`. Using `-fomit-frame-pointer` with Clang cuts about 2-3% off the `libQt5Core.so` size. I see an LLVM issue discussing this flag (https://bugs.llvm.org/show_bug.cgi?id=32501 and https://reviews.llvm.org/D31972).

 * I isolated a small piece of code where Clang wastes 3 instructions (6 bytes of a 44 byte function) doing comparisons inefficiently. https://godbolt.org/g/BPRZM8

 * `clang -Os` seems to inline a lot more than `gcc -Os`, whereas `clang -Oz` inlines much less. Clang has options for tuning the inlining, like `-mllvm -inline-threshold=<nnn>` and `-mllvm -inlinehint-threshold=<nnn>`.

   ```
   $ fncount() { find "$1" -name '*.o' | xargs readelf -s -W | grep ' FUNC ' | grep -v ' UND ' | wc -l; }
   $ fncount out-Os/src/corelib/.obj
   10965
   $ fncount out-gcc/src/corelib/.obj
   12055
   $ fncount out-Os-inl-15-40/src/corelib/.obj
   12927
   $ fncount out-Oz/src/corelib/.obj
   15105
   ```

 * Building with `-Os -mllvm -inline-threshold=15 -mllvm -inlinehint-threshold=40` gets close to `-Oz`:
   ```
   -rwxr-x--- 1 rprichard eng 4071432 Dec 15 16:45 out-Os-inl-15-40/core.so.stripped
   ```
   (There's nothing special about these two thresholds. 15 was low enough to prevent wasteful inlining in`qbuffer.o`.)

 * The `.ARM.extab` section is much bigger with Clang. I haven't looked into it yet. (Something related to exceptions, I assume?)

 * Normally ARM64 Android Qt is built with `-O2`. Clang's binary is a little smaller:
   ```
   -rwxr-x--- 1 rprichard eng 6208944 Dec 15 17:09 out64-gcc-O2/core.so.stripped
   -rwxr-x--- 1 rprichard eng 6166424 Dec 15 17:09 out64-O2/core.so.stripped
   ```
   I changed `mkspecs/common/android-base-tail.conf` to test `-Os`. Clang's binary is still smaller:
   ```
   -rwxr-x--- 1 rprichard eng 6159792 Dec 15 16:55 out64-gcc-Os/core.so.stripped
   -rwxr-x--- 1 rprichard eng 6035352 Dec 15 16:55 out64-Os/core.so.stripped
   ```

   The ARM64 binaries are about 50% bigger than the ARM32 ones.

**Comment by rprichard** [comment]
Firefox has switched to using Clang by default: https://bugzilla.mozilla.org/show_bug.cgi?id=1163171. Regarding code size:

https://bugzilla.mozilla.org/show_bug.cgi?id=1163171#c14:

> clang 5.0 (NDK 15b) with -Oz (but turn off elfhack since elfhack throws assertion)
> 32754501 Jul  6 09:52 fennec-56.0a1.en-US.android-arm.apk
> 
> gcc 4.9 (NDK 15b)
> 32918280 Jul  6 10:19 fennec-56.0a1.en-US.android-arm.apk
>
>
> clang w/ -Oz is smaller than gcc w/ -Os.

**Comment by rprichard** [comment]
Something else to look at: try fixing/reenabling the `-arm-promote-constant` optimization (https://github.com/android-ndk/ndk/issues/642).

**Comment by enh** [comment]
given that firefox has switched, should we move remaining issues to a separate Qt bug?

**Comment by DanAlbert** [comment]
The fundamental issues here are still present. Firefox switched *despite* this issue, not because the issue is fixed aiui.

@rprichard it looks like you still have a handful of things mentioned above that you want to investigate. Up to you if you want to split those out into separate bugs and close this one.

**Comment by DanAlbert** [comment]
Oh, never mind. Missed the update showing that `-Oz` outperformed GCC. There are still a couple other avenues for improving things further here though, so if we're going to close this it should be while also opening other bugs to track those.

**Comment by enh** [comment]
we should probably update https://android.googlesource.com/platform/ndk/+/master/docs/ClangMigration.md too with some of the other tips. (and make it more findable. i have to search for "Clang Migration Notes" rather than "NDK clang migration" to find it, and i never remember that. i usually end up finding it by browsing the source tree :-/ .)

actually, maybe we should just have a more general "Things that affect your binary size" page --- much of this stuff (such as `-Bsymbolic` or `-ffunction-sections`) will still be useful even in the distant future when no-one's thinking in terms of "migration".

**Comment by rprichard** [comment]
https://github.com/android-ndk/ndk/issues/573 is fixed now, so I think we could switch the NDK build systems' defaults back to `-Oz`.

**Comment by DanAlbert** [comment]
Yeah, I'll do that.

**Comment by enh** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/708632 switched us back to -Oz, so this is fixed in r18?

**Comment by rprichard** [comment]
I think there's more work we could do here, but maybe we can close it. It's an open-ended bug report.
 - r18 also includes my EH table size reduction (https://reviews.llvm.org/D43001)
 - Clang still forces a frame pointer on arm32, whereas gcc didn't. (I saw a 2-3% reduction by adding `-fomit-frame-pointer`.)
 - I just retested `libQtCore.so` with r18's Clang, and the binary is still 7.3% bigger than GCC's. (It's only 4.0% bigger if I build with `-Oz -fomit-frame-pointer`.)
 - Looking at all the Qt solibs combined, r18's Clang binaries are 3.9% bigger than GCC's and 1.0% bigger with `-Oz -fomit-frame-pointer`.

**Comment by rprichard** [comment]
I measured Qt5 sizes again using the 5.11.1 tag and this patch, which is needed to work with the per-API linker scripts (https://github.com/android-ndk/ndk/issues/672). It seems that `-lc++` doesn't work anymore, but Qt always links libc++ dynamically, so I changed `qmake.conf` to look for a particular `libc++.so` linker script, with either r18 or an earlier NDK:

```diff
diff --git a/mkspecs/android-clang/qmake.conf b/mkspecs/android-clang/qmake.conf
index b665000d00..b136bb0be4 100644
--- a/mkspecs/android-clang/qmake.conf
+++ b/mkspecs/android-clang/qmake.conf
@@ -40,7 +40,8 @@ QMAKE_CFLAGS += -DANDROID_HAS_WSTRING --sysroot=$$NDK_ROOT/sysroot \
 ANDROID_SOURCES_CXX_STL_LIBDIR = $$NDK_ROOT/sources/cxx-stl/llvm-libc++/libs/$$ANDROID_TARGET_ARCH
 
 ANDROID_STDCPP_PATH = $$ANDROID_SOURCES_CXX_STL_LIBDIR/libc++_shared.so
-ANDROID_CXX_STL_LIBS = -lc++
+ANDROID_CXX_STL_LIBS = $$ANDROID_SOURCES_CXX_STL_LIBDIR/libc++.so.$$replace(ANDROID_PLATFORM, "android-", "")
+!exists($$ANDROID_CXX_STL_LIBS): ANDROID_CXX_STL_LIBS = $$ANDROID_SOURCES_CXX_STL_LIBDIR/libc++.so
 
 QMAKE_CFLAGS_OPTIMIZE_SIZE = -Oz
 
```

I used GCC from r17b and Clang from r18 build 4855205, and I targeted either android-16 or android-21. For Clang, I added `-fomit-frame-pointer` to `QMAKE_CFLAGS_OPTIMIZE_SIZE` to match GCC's behavior. android-21 binaries are smaller because they aren't linked with `libandroid_support.a`. (I wouldn't think android-21 would be the default SDK minimum because AFAICT it's going to exclude 15% of active devices, but it was used above and on https://wiki.qt.io/Android.)

API 16:


  | GCC | Clang | Change | Change(Pct)
-- | -- | -- | -- | --
libQt5Concurrent | 13712 | 18192 | 4480 | 32.67%
libQt5Core | 3759300 | 3816628 | 57328 | 1.52%
libQt5Gui | 2864572 | 2856168 | -8404 | -0.29%
libQt5Network | 611792 | 604324 | -7468 | -1.22%
libQt5OpenGL | 218484 | 218712 | 228 | 0.10%
libQt5PrintSupport | 247204 | 250792 | 3588 | 1.45%
libQt5Sql | 128372 | 131564 | 3192 | 2.49%
libQt5Test | 177708 | 183896 | 6188 | 3.48%
libQt5Widgets | 3622528 | 3608236 | -14292 | -0.39%
libQt5Xml | 128360 | 129672 | 1312 | 1.02%
TOTAL | 11772032 | 11818184 | 46152 | 0.39%

API 21:


  | GCC | Clang | Change | Change(Pct)
-- | -- | -- | -- | --
libQt5Concurrent | 13712 | 18192 | 4480 | 32.67%
libQt5Core | 3759300 | 3804328 | 45028 | 1.20%
libQt5Gui | 2864572 | 2847976 | -16596 | -0.58%
libQt5Network | 611792 | 604328 | -7464 | -1.22%
libQt5OpenGL | 218484 | 218712 | 228 | 0.10%
libQt5PrintSupport | 247204 | 246700 | -504 | -0.20%
libQt5Sql | 128372 | 131564 | 3192 | 2.49%
libQt5Test | 177708 | 183908 | 6200 | 3.49%
libQt5Widgets | 3622528 | 3600048 | -22480 | -0.62%
libQt5Xml | 128360 | 129672 | 1312 | 1.02%
TOTAL | 11772032 | 11785428 | 13396 | 0.11%

**Comment by perracolabs** [comment]
I understand the arm64-v8a binaries are larger than armeabi-v7a, but, is it normal they are all between 20% to 30% larger than the v7a version? This is what I'm getting, same code same compilation, yet 20% to 30% size difference per binary.

**Comment by enh** [comment]
armv7 has the https://en.wikipedia.org/wiki/ARM_architecture#Thumb compressed encoding so many common instructions will be 16-bit. armv8 has no compressed encoding so every instruction is 32-bit.

**Comment by stephenhines** [comment]
20-30% is within the realm of what we see for 32-bit vs. 64-bit as well, so this isn't unexpected.

**Comment by DanAlbert** [comment]
The only open question remaining here is whether `-fomit-frame-pointer` should be the default: https://github.com/android-ndk/ndk/issues/824.
