### ISSUE TITLE
Compile error when including <complex>

### ISSUE THREAD

**Issue by DoDoENT** [android-ndk/ndk#15]
Error:

```
~/android-ndk-r11/sources/cxx-stl/gnu-libstdc++/4.9/include/complex:53:45: error: missing terminating ' character [-Werror]
 #error Cannot include both <complex> and C99's <complex.h>
```

This can be fixed by changing lines 52-54 of `$NDK_DIR/sources/cxx-stl/gnu-libstdc++/4.9/include/complex`

from

```c++
#ifdef _GLIBCXX_C99_COMPLEX_H
#error Cannot include both <complex> and C99's <complex.h>
#endif
```
into 
```c++
#ifdef _GLIBCXX_C99_COMPLEX_H
#error Cannot include both <complex> and C99 <complex.h>
#endif
```

**Comment by DanAlbert** [comment]
@thanm, that block doesn't exist in the upstream GCC at all. Instead there's just

```cpp
// Get rid of a macro possibly defined in <complex.h>
#undef complex
```

**Comment by DanAlbert** [comment]
Looks like cmtice actually fixed this when synchronizing us with the ChromeOS GCC, so this is already fixed for r12.

**Comment by DoDoENT** [comment]
I just updated to r11b and this issue is still present. I see now that it has been set to the r12 milestone. When is approximate release date for r12?

**Comment by DanAlbert** [comment]
Should have a beta release early April. We've never actually done one of these before, so we'll see how that goes :)

Stable release will be in June.
