### ISSUE TITLE
exception handling doesn't work with static executables

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#593]
Currently undiagnosed. Since it's a static executable, we don't get a stack trace in logcat.

**Comment by leebaok** [comment]
So exceptions not work with libc++ static ?
But for gnustl ? can exceptions work ?
@DanAlbert

**Comment by jmgao** [comment]
re: no stack traces in logcat, try gdbclient?

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/bionic/+/600854

**Comment by DanAlbert** [comment]
The patch above fixes arm32. The other architectures (arm64 at least, I haven't gotten to testing the Intel arches yet, but the fix is likely the same) are broken because Clang doesn't automatically pass `--eh-frame-hdr` to the linker for static executables: https://android.googlesource.com/toolchain/clang/+/0659c9e0352a35af1ea86cf11b19618543702974/lib/Driver/ToolChains/Gnu.cpp#368

This actually isn't unique to libc++. Exceptions don't work for any STL with static executables because of this.

I'm trying to dig into why Clang doesn't do that and get it fixed, but that will require a clang update. Until then, you can use exceptions in static executables by adding `-Wl,--eh-frame-hdr` to your ldflags.

**Comment by leebaok** [comment]
@DanAlbert  Hi, we use ndk-r16b with the patch above, but exception still not works for static linking with libc++.

We use gcc/g++ with libc++ library:
* when linking with `-static -lc++_static -lc++abi -lunwind -lgcc`, it reports `terminating with uncaught exception of ...` 
* when linking with `-static -lc++_static -lc++abi -lgcc` (use gcc exception handler), it reports : 
```
PC: 0x27b40 = <_Unwind_GetLanguageSpecificData>+0xc/0x1c, SP:0x56ca8, FP:0x1, SP_BOTTOM:0x57000
 30 [0x56cac] 0x9579 = <_ZN10__cxxabiv1L11scan_eh_tabERNS_12_GLOBAL__N_112scan_resultsE14_Unwind_ActionbP21_Unwind_Control_BlockP15_Unwind_Context>+0x70/0x3e4 ?
 31 [0x56cec] 0x27acc = <__gnu_unwind_execute>+0x37c/0x398 ?
 32 [0x56d14] 0x93d7 = <__gxx_personality_v0>+0x72/0x1a4 ?
 33 [0x56d1c] 0x2711c = <__gnu_unwind_pr_common>+0x364/0x3ec ?
 34 [0x56d64] 0x26ae0 = <__gnu_Unwind_RaiseException>+0x6c/0xa4 ?
 35 [0x56d70] 0x8dfd = <__cxa_throw>+0x64/0x68 ?
 36 [0x56da4] 0x8d14 = <test_cxx>+0x30/0x78 ?
```

So, is there any problems with my usage ? or is there still some bugs in the static linking with libc++ ?

Thanks.

**Comment by leebaok** [comment]
Hi, @DanAlbert 

the above patch may be not correct. `pcount` of `__gnu_Unwind_Find_exidx` means the length of `ARM.exidx` section, it should be the bytes of the section, so just `&__exidx_end - &__exidx_start`, should not be divided by 8.

`__gnu_Unwind_Find_exidx` is used by linunwind ( libunwind/src/AddressSpace.hpp : about line 370 ): 
```
int length = 0;
info.arm_section = (uintptr_t) dl_unwind_find_exidx(
     (_Unwind_Ptr) targetAddr, &length);
info.arm_section_length = (uintptr_t)length;
```
`dl_unwind_find_exidx` means `__gnu_Unwind_Find_exidx`, so `pcount` is the section length.

so, the `__gnu_Unwind_Find_exidx` should be below:
```
_Unwind_Ptr __gnu_Unwind_Find_exidx(_Unwind_Ptr pc __attribute__((unused)), int* pcount) {
  *pcount = &__exidx_end - &__exidx_start;
  return (_Unwind_Ptr)&__exidx_start;
}
```

**Comment by eddielong** [comment]
I'm encountering this problem too (using zxing which heavily uses exceptions for not detecting barcodes, yuck), looking at that link above, do you know when or in what NDK the fix will be released?

**Comment by DanAlbert** [comment]
The milestone is accurate. This is fixed in r17, but not necessarily in beta 1.

**Comment by DanAlbert** [comment]
The arm32 fix is now in r17 (will be in beta 1 since we're respinning that for a gradle workaround). The --eh-frame-hdr issue has a patch up for clang (https://reviews.llvm.org/D43203), but that won't land in the NDK until at least r18. We can still do a bit more work for r17 to add `-Wl,--eh-frame-hdr` to the default ldflags for CMake and ndk-build, but that won't be in beta 1.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/618577 hoists this into the build systems until we get a clang with the fix.

**Comment by DanAlbert** [comment]
r17 beta 1 is being respun again, so this will be in after all. I'll leave the bug open to track the clang fix, but I'm moving this off the r17 milestone since we've done as much as we can for this release.

**Comment by DanAlbert** [comment]
Change is submitted upstream. Over to @stephenhines to get the change into the next clang update.

**Comment by DanAlbert** [comment]
Fixed in r17.

**Comment by FrankHB** [comment]
@DanAlbert This is not fully fixed for old platforms (tested with NDK r20, target platform v21), because the definition of `__gnu_Unwind_Find_exidx` actually used by libc++ is still broken. It seems that the broken definition comes from the dynamically linked system libc .

Since statically linked libc is problematic, I have to backport [this](https://github.com/aosp-mirror/platform_bionic/commit/aeb5bc658feaa579b72560a7026374cbeb38ea56) and pass `-Wl,--wrap=__gnu_Unwind_Find_exidx` to the linker command with explicitly specified `crtbegin_so`/`crtend_so` stuff to allow the object file containing the wrapper after `-lc++`, and it works.

**Comment by DanAlbert** [comment]
> It seems that the broken definition comes from the dynamically linked system libc .

Then it sounds like you aren't using a static executable. Could you verify that?

**Comment by FrankHB** [comment]
@DanAlbert My fault. I was testing the standalone toolchain with different project configurations and occasionally got confused by makefiles having different linker flags (`-shared`/`-static`/`-static -static-libstdc++`/nothing).

The previously mentioned problem still exists in the configuration with a single `.so` linked with `-static-libstdc++` loaded by `NativeActivity`. This should be indeed another topic, but let me summarize a little here. AFAIK the failure is due to a call to an unexpected personality routine in the unwinding phase 1, which should not happen after following [the document](https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#Unwinding). The failure only occur within some specific position of my code. (Not sure if [this](https://bugs.llvm.org/show_bug.cgi?id=21053) and [this](http://lists.llvm.org/pipermail/cfe-dev/2018-February/057014.html) are related.) Since the original case is not easy to reduce, I'm still investigating the exact condition to reproduce the problem. I'd open an issue then. Sorry for the misreport.

**Comment by DanAlbert** [comment]
Yeah, go ahead and open a new bug if you find something. It's almost always a broken dependency in this situation.

**Comment by FrankHB** [comment]
I find it a code generation issue, reported [upstream](https://bugs.llvm.org/show_bug.cgi?id=43275).

**Comment by DanAlbert** [comment]
Thanks! I filed https://github.com/android/ndk/issues/1079 to track that on our side.
