### ISSUE TITLE
NDK 17: undefined reference to 'pthread_attr_setinheritsched'

### ISSUE THREAD

**Issue by RichDove** [android-ndk/ndk#716]
#### Description

NDK 17 has added declaration of 'pthread_attr_setinheritsched' function to pthread.h. But attempt to use this function produces undefined reference to 'pthread_attr_setinheritsched' linker error:

[x86_64] SharedLibrary  : libsvc_jni.so
  /dev/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -Wl,-soname,libsvc_jni.so -shared --sysroot=/dev/android-ndk-r17/platforms/android-27/arch-x86_64 @/src/apps/android//Svc/build/intermediates/ndkBuild/debug/obj/local/x86_64/objs-debug/svc_jni/linker.list  -gcc-toolchain /dev/android-ndk-r17/toolchains/x86_64-4.9/prebuilt/linux-x86_64 -target x86_64-none-linux-android -no-canonical-prefixes   -Wl,--build-id -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings  -L/dev/android-ndk-r17/platforms/android-27/arch-x86_64/usr/lib64 -L/dev/android-ndk-r17/platforms/android-27/arch-x86_64/usr/lib -llog -lc -lm -o /src/apps/android//Svc/build/intermediates/ndkBuild/debug/obj/local/x86_64/libsvc_jni.so
  /src/apps/android//Svc/src/main/jni/../../../../../../../common/libutils/code/src/threads.cc:102: error: undefined reference to 'pthread_attr_setinheritsched'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  make: *** [/src/apps/android//Svc/build/intermediates/ndkBuild/debug/obj/local/x86_64/libsvc_jni.so] Error 1

#### Environment Details

* NDK Version: NDK 17
* Host OS: Ubuntu 14.04 x86
* Compiler: any
* ABI: any
* STL: stlport_static
* NDK API level: any > 21

**Comment by enh** [comment]
d'oh! how did we screw this up? it was added in P and we told the *linker* this (in libc.so), but we didn't tell the compiler (in pthread.h). sorry. will fix.

**Comment by DanAlbert** [comment]
If you're quick we can maybe squeeze this into r17b. I'm not sure if that's gone to QA yet.

**Comment by DanAlbert** [comment]
Just came up in the meeting and no, QA hasn't started on this yet. They expect they'll be able to today or tomorrow though, so I've asked that they hold off until we get a change in for this.

**Comment by enh** [comment]
CL up for review: https://android-review.googlesource.com/c/platform/bionic/+/701332

**Comment by DanAlbert** [comment]
Fixed in r17b.

**Comment by Sinket** [comment]
I see this has been closed for awhile but would it be probable that it still occurs?

> /Users/admin/Projects/Demo/build/vision-build-arm-linux-androideabi/vision_linux.o:vision_linux.c:function vis_mutex_init: error: undefined reference to 'pthread_mutexattr_setprotocol'
> /Users/admin/Projects/Demo/build/vision-build-arm-linux-androideabi/vision_linux.o:vision_linux.c:function vis_thread_create: error: undefined reference to 'pthread_attr_setinheritsched'
> /Users/admin/Projects/Demo/build/vision-build-arm-linux-androideabi/vision_linux.o:vision_linux.c:function vis_thread_create: error: undefined reference to 'pthread_attr_setinheritsched'
> /Users/admin/Projects/Demo/build/vision-build-arm-linux-androideabi/vision_linux.o:vision_linux.c:function vis_thread_create: error: undefined reference to 'pthread_attr_setinheritsched'

Env:
Mac OS 10.14.6
NDK: 20.0.5594570
Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Users/admin/Dev/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin

**Comment by enh-google** [comment]
that function isn't available until API level 28. the "fix" here was just to make this a compile-time error rather than a link-time error (as long as you tell the compiler which API level you're targeting).
